spring:
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/loja?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
